name: "ProjectCi"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
      DATABASE_URL: mongodb://localhost/nasa
      PORT: 8000
      LAUNCHESDATA_API_URL: "https://api.spacexdata.com/v4/launches/query"
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --prefix frontend
      - name: Use Mongo forro tests
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run test --prefix backend
